name: Fetch Coins

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Execute a program
        env:
          NOTION_ACCESS_TOKEN: ${{ secrets.NOTION_ACCESS_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          CMC_PRO_API_KEY: ${{ secrets.CMC_PRO_API_KEY }}
          CMC_PRO_API_URL: ${{ secrets.CMC_PRO_API_URL }}
        run: deno run  --allow-env --allow-net src/index.ts
